[package]
name = "signal-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
lazy_static = "1.4.0"
config = "0.14.0"

[build-dependencies]